version: '3'

volumes:
  postgres:

services:
  db:
    image: postgres:12
    container_name: "kenshu-php-db"
    environment:
      - POSTGRES_DB=${DB}
      - POSTGRES_USER=${USERNAME}
      - POSTGRES_PASSWORD=${PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./configs/postgres/initdb.d:/docker-entrypoint-initdb.d

  web:
    build: .
    container_name: "kenshu-php-web"
    env_file:
      - .env
    volumes:
      - "./web:/var/www/html"
      - "./configs/php/php.ini:/usr/local/etc/php/php.ini"
    ports:
      - "8080:80"
    depends_on:
      - db
